# Generated by Django 3.0.5 on 2020-09-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=45)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(max_length=45)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cliente', models.IntegerField(default=0)),
                ('repartidor', models.IntegerField(default=0)),
                ('formadepago', models.IntegerField(default=0)),
            ],
        ),
    ]
